import { 
  HiOutlineLogin, HiOutlineLogout, HiOutlineExclamationCircle, 
  HiOutlineCheckCircle, HiOutlineShieldCheck, HiOutlineUser, 
  HiOutlineMail, HiOutlineLockClosed, HiOutlineMenu, HiOutlineX, 
  HiOutlineCheck, HiOutlineInformationCircle, HiOutlineViewGrid, 
  HiOutlineBookOpen, HiOutlineTrash, HiOutlineCog, HiOutlineRefresh, 
  HiOutlineEye, HiOutlineHome, HiOutlineUsers, HiOutlineClipboardList,
  HiOutlineChevronLeft, HiOutlineChevronRight, HiOutlineSearch,
  HiOutlineFilter, HiOutlineDotsVertical, HiOutlinePencilAlt,
  HiOutlineBan, HiOutlineClock, HiOutlineStar, HiOutlineTrendingUp,
  HiOutlineCalendar, HiOutlineChartBar, HiOutlineCollection
} from 'react-icons/hi';
import { FaUserCheck, FaRegUser, FaSpinner, FaUsers, FaBookOpen, FaRegCalendarCheck, FaUserTie } from 'react-icons/fa';

export const Icons = {
  login: HiOutlineLogin,
  logout: HiOutlineLogout,
  exclamationCircle: HiOutlineExclamationCircle,
  checkCircle: HiOutlineCheckCircle,
  shieldCheck: HiOutlineShieldCheck,
  user: HiOutlineUser,
  mail: HiOutlineMail,
  lock: HiOutlineLockClosed,
  menu: HiOutlineMenu,
  close: HiOutlineX,
  check: HiOutlineCheck,
  infoCircle: HiOutlineInformationCircle,
  dashboard: HiOutlineViewGrid,
  book: HiOutlineBookOpen,
  trash: HiOutlineTrash,
  settings: HiOutlineCog,
  refresh: HiOutlineRefresh,
  eye: HiOutlineEye,
  userCheck: FaUserCheck,
  userOutline: FaRegUser,
  spinner: FaSpinner,
  home: HiOutlineHome,
  users: HiOutlineUsers,
  clipBoard: HiOutlineClipboardList,
  chevronLeft: HiOutlineChevronLeft,
  chevronRight: HiOutlineChevronRight,
  search: HiOutlineSearch,
  filter: HiOutlineFilter,
  dotsVertical: HiOutlineDotsVertical,
  edit: HiOutlinePencilAlt,
  ban: HiOutlineBan,
  clock: HiOutlineClock,
  star: HiOutlineStar,
  trendingUp: HiOutlineTrendingUp,
  calendar: HiOutlineCalendar,
  chartBar: HiOutlineChartBar,
  collection: HiOutlineCollection,
  faUsers: FaUsers,
  faBookOpen: FaBookOpen,
  faCalendarCheck: FaRegCalendarCheck,
  faUserTie: FaUserTie,
};

export default Icons;
