import {
  HiOutlineMenu,
  HiOutlineX,
  HiOutlineChevronDown,
  HiOutlineArrowLeft,
  HiOutlineArrowRight,
  HiOutlineUser,
  HiOutlineUserAdd,
  HiOutlineUserGroup,
  HiOutlineLogin,
  HiOutlineLogout,
  HiOutlineLockClosed,
  HiOutlineMail,
  HiOutlineBookOpen,
  HiOutlinePencil,
  HiOutlineTrash,
  HiOutlineClock,
  HiOutlineCheck,
  HiOutlineSave,
  HiOutlineRefresh,
  HiOutlineLink,
  HiOutlineCheckCircle,
  HiOutlineExclamationCircle,
  HiOutlineInformationCircle,
  HiOutlineSparkles,
  HiOutlineSearch,
  HiOutlineHome,
  HiOutlineViewGrid,
  HiOutlineShieldCheck,
  HiOutlineBell,
  HiCamera,
  HiEye,
  HiOutlineGlobe,
  HiOutlinePhone,
  HiOutlineChat,
  HiOutlineShare,
  HiOutlineAcademicCap,
  HiOutlineBriefcase,
  HiOutlineCalendar,
  HiOutlineCurrencyDollar,
  HiOutlinePlus,
} from 'react-icons/hi';
import { FaStar, FaRegStar, FaSpinner, FaRegHeart, FaHeart } from 'react-icons/fa';
import { MdVerified, MdPending } from 'react-icons/md';

export const Icons = {
  home: HiOutlineHome,
  menu: HiOutlineMenu,
  close: HiOutlineX,
  chevronDown: HiOutlineChevronDown,
  arrowLeft: HiOutlineArrowLeft,
  arrowRight: HiOutlineArrowRight,

  user: HiOutlineUser,
  userAdd: HiOutlineUserAdd,
  category: HiOutlineUserGroup,
  login: HiOutlineLogin,
  logout: HiOutlineLogout,

  lock: HiOutlineLockClosed,
  mail: HiOutlineMail,
  book: HiOutlineBookOpen,
  edit: HiOutlinePencil,
  trash: HiOutlineTrash,
  clock: HiOutlineClock,
  check: HiOutlineCheck,
  save: HiOutlineSave,
  refresh: HiOutlineRefresh,
  link: HiOutlineLink,

  checkCircle: HiOutlineCheckCircle,
  exclamationCircle: HiOutlineExclamationCircle,
  infoCircle: HiOutlineInformationCircle,
  sparkles: HiOutlineSparkles,
  search: HiOutlineSearch,
  dashboard: HiOutlineViewGrid,
  shieldCheck: HiOutlineShieldCheck,
  camera: HiCamera,
  eye: HiEye,
  globe: HiOutlineGlobe,
  phone: HiOutlinePhone,
  chat: HiOutlineChat,
  share: HiOutlineShare,

  academic: HiOutlineAcademicCap,
  briefcase: HiOutlineBriefcase,
  calendar: HiOutlineCalendar,
  money: HiOutlineCurrencyDollar,
  plus: HiOutlinePlus,
  bell: HiOutlineBell,

  starSolid: FaStar,
  starRegular: FaRegStar,
  heartSolid: FaHeart,
  heartRegular: FaRegHeart,
  spinner: FaSpinner,

  verified: MdVerified,
  pending: MdPending,
};

export default Icons;
