import Story from "./models/Story.js";
import Like from "./models/Like.js";
import Comment from "./models/Comment.js";
import Follow from "../following/model.js";
import Author from "../author/model.js";
import { generateContent } from "../shared/services/llm.js";
import {
  getStoryAnalysisPrompt,
  getGrammarCorrectionPrompt,
  getSummaryPrompt,
  getLanguageDetectionPrompt,
} from "../shared/prompts/story.js";
import { uploadStoryImage, uploadAvatar } from "../shared/services/upload.js";
import { NotFoundError, ValidationError } from "../shared/utils/errors.js";
import { extractTextFromDocument } from "../shared/utils/helpers.js";
import slugify from "slugify";

// Helper to get plain text snippet from document for preview purposes
function getDocPreview(doc, maxLen = 100) {
  const text = extractTextFromDocument(doc);
  if (!text) return "";
  return text.length > maxLen ? text.slice(0, maxLen) + "..." : text;
}

export async function uploadImage(req, res, next) {
  try {
    if (!req.file) {
      throw new ValidationError("No image file provided.");
    }

    const uploaded = await uploadStoryImage(req.file.buffer);

    res.json({
      success: true,
      data: {
        url: uploaded.url,
        publicId: uploaded.publicId,
      },
    });
  } catch (error) {
    next(error);
  }
}

export async function create(req, res, next) {
  try {
    // Handle document which may be a JSON string (from FormData) or an object (from JSON API)
    let document = req.body.document;
    if (typeof document === "string") {
      try { document = JSON.parse(document); } catch { /* keep as-is */ }
    }
    if (!document || typeof document !== "object") {
      document = { type: "doc", content: [] };
    }
    const { title = "", storyType = "autobiography" } = req.body;

    const cleanTitle = title?.trim() || "";

    // Handle cover image upload if provided
    let coverImage = {};
    if (req.file) {
      const uploaded = await uploadStoryImage(req.file.buffer);
      coverImage = { url: uploaded.url, publicId: uploaded.publicId };
    }

    // Slug is auto-generated by the model's pre-save hook
    const story = await Story.create({
      author: req.user.id,
      document,
      title: cleanTitle,
      storyType,
      coverImage,
    });

    res.status(201).json({
      success: true,
      data: story,
    });
  } catch (error) {
    next(error);
  }
}

export async function update(req, res, next) {
  try {
    const { storyId } = req.params;

    const story = await Story.findOne({
      _id: storyId,
      author: req.user.id,
    });

    if (!story) {
      throw new NotFoundError("Story not found.");
    }

    if (!["draft", "rejected", "published"].includes(story.status)) {
      throw new ValidationError(
        "This story cannot be edited in its current state.",
      );
    }

    let { title, storyType } = req.body;
    let document = req.body.document;
    
    // Handle document which may be a JSON string (from FormData) or an object (from JSON API)
    if (document !== undefined && typeof document === "string") {
      try { document = JSON.parse(document); } catch { /* keep as-is */ }
    }

    if (document !== undefined) {
      story.document = document;
    }

    if (title !== undefined) {
      const cleanTitle = title.trim();
      story.title = cleanTitle;
      // Slug is auto-generated by the model's pre-save hook when title changes
    }

    if (storyType !== undefined) {
      story.storyType = storyType;
    }

    // Handle cover image upload if provided
    if (req.file) {
      const uploaded = await uploadStoryImage(req.file.buffer);
      story.coverImage = { url: uploaded.url, publicId: uploaded.publicId };
    }

    // If story was rejected and author saves as draft, reset to draft
    if (story.status === "rejected") {
      story.status = "draft";
      story.verification.issues = [];
      story.verification.canProceed = true;
    }

    await story.save();

    res.json({
      success: true,
      data: story,
    });
  } catch (error) {
    next(error);
  }
}

export async function verify(req, res, next) {
  try {
    const { storyId } = req.params;
    const { keepPublished } = req.body;

    const story = await Story.findOne({
      _id: storyId,
      author: req.user.id,
    });

    if (!story) {
      throw new NotFoundError("Story not found.");
    }

    const plainText = extractTextFromDocument(story.document);
    if (!plainText) {
      throw new ValidationError("Story content is required for verification.");
    }

    // Run AI content moderation analysis synchronously
    const result = JSON.parse(
      await generateContent({
        system: getStoryAnalysisPrompt(),
        prompt: plainText,
        json: true,
      }),
    );

    // Store verification result on the story
    story.verification.status = "completed";
    story.verification.canProceed = result.canProceed;
    story.verification.issues = result.issues ?? [];

    if (result.canProceed) {
      // If keepPublished is set and story was published, keep it published
      story.status = keepPublished ? "published" : "verified";
    } else {
      story.status = "rejected";
    }

    await story.save();

    res.json({
      success: true,
      data: {
        canProceed: result.canProceed,
        issues: result.issues ?? [],
        overallAssessment: result.overallAssessment ?? "",
      },
    });
  } catch (error) {
    next(error);
  }
}

export async function publish(req, res, next) {
  try {
    const { storyId } = req.params;

    const story = await Story.findOne({
      _id: storyId,
      author: req.user.id,
    });

    if (!story) {
      throw new NotFoundError("Story not found.");
    }

    if (story.status !== "verified") {
      throw new ValidationError(
        "Story must pass AI verification before publishing.",
      );
    }

    const plainText = extractTextFromDocument(story.document);
    if (!plainText) {
      throw new ValidationError("Story content is required.");
    }

    if (!story.title?.trim()) {
      throw new ValidationError("Story title is required before publishing.");
    }

    // 1. Language detection
    const langResult = JSON.parse(
      await generateContent({
        system: getLanguageDetectionPrompt(),
        prompt: plainText.substring(0, 2000),
        json: true,
      }),
    );

    story.language = langResult.language || "English";

    // 2. Grammar correction
    const corrected = await generateContent({
      system: getGrammarCorrectionPrompt(langResult.language || "English"),
      prompt: plainText,
    });

    // 3. Summary generation
    const summary = await generateContent({
      system: getSummaryPrompt(),
      prompt: corrected,
    });

    // Save everything
    story.summary.status = "completed";
    story.summary.content = summary.trim();
    story.status = "published";
    story.publishedAt = new Date();

    // Ensure slug exists
    if (!story.slug && story.title) {
      story.slug = slugify(story.title, { lower: true, strict: true, trim: true });
    }

    // Increment author stats
    await Author.findByIdAndUpdate(story.author, {
      $inc: { "stats.stories": 1 },
    });

    await story.save();

    res.json({
      success: true,
      data: story,
    });
  } catch (error) {
    next(error);
  }
}

export async function remove(req, res, next) {
  try {
    const { storyId } = req.params;

    const story = await Story.findOne({
      _id: storyId,
      author: req.user.id,
    });

    if (!story) {
      throw new NotFoundError("Story not found.");
    }

    if (!["draft", "rejected"].includes(story.status)) {
      throw new ValidationError(
        "Only draft or rejected stories can be deleted.",
      );
    }

    await story.deleteOne();

    res.json({
      success: true,
      message: "Story deleted successfully.",
    });
  } catch (error) {
    next(error);
  }
}

export async function getStory(req, res, next) {
  try {
    const { storyId } = req.params;

    // Support both slug and ID lookups
    const filter = { status: "published" };
    
    // Check if it's a valid ObjectId (24 hex chars) or a slug
    const isObjectId = /^[0-9a-fA-F]{24}$/.test(storyId);
    
    if (isObjectId) {
      filter._id = storyId;
    } else {
      filter.slug = storyId;
    }

    const story = await Story.findOne(filter)
      .populate("author", "fullName username avatar bio profession stats socialLinks")
      .lean();

    if (!story) {
      throw new NotFoundError("Story not found.");
    }

    // Check if the requesting user has liked this story
    let likedByUser = false;
    let followingAuthor = false;
    if (req.user) {
      const existing = await Like.findOne({
        story: story._id,
        user: req.user.id,
      });
      likedByUser = !!existing;

      // Check if user follows the author
      if (req.role === "user") {
        const followExists = await Follow.findOne({
          who: req.user.id,
          whom: story.author?._id || story.author,
        });
        followingAuthor = !!followExists;
      }
    }

    res.json({
      success: true,
      data: {
        ...story,
        likedByUser,
        followingAuthor,
      },
    });
  } catch (error) {
    next(error);
  }
}

export async function list(req, res, next) {
  try {
    const type = req.query.type;

    const page = Math.max(Number(req.query.page) || 1, 1);
    const limit = type === "latest" || type === "trending"
        ? 10
        : Math.min(Number(req.query.limit) || 20, 50);

    const filter = {
      status: "published",
    };

    // Support filtering by author for profile pages
    if (req.query.author) {
      filter.author = req.query.author;
    }

    // Support full-text search by query (used by /search and feed search)
    const q = req.query.q?.trim();
    if (q) {
      const escapeRegex = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      const pattern = new RegExp(escapeRegex(q), "i");
      filter.$or = [{ title: pattern }, { slug: pattern }, { "summary.content": pattern }];
    }

    // Select only needed fields for the feed listing
    let query = Story.find(filter)
      .select("title slug summary document coverImage author storyType language stats publishedAt createdAt")
      .populate("author", "fullName username avatar profession");

    if (type === "trending") {
      query = query.sort({
        "stats.likes": -1,
        "stats.comments": -1,
        publishedAt: -1,
      });
    } else {
      query = query.sort({ publishedAt: -1 });
    }

    const [stories, total] = await Promise.all([
      query
        .skip(type ? 0 : (page - 1) * limit)
        .limit(limit)
        .lean(),

      Story.countDocuments(filter),
    ]);

    // Check follow status, like status, and recent likers
    let followingMap = {};
    let likedMap = {};
    const recentLikersMap = {};
    
    if (req.user && req.role === "user") {
      const storyIds = stories.map(s => s._id.toString()).filter(Boolean);
      const authorIds = stories.map(s => s.author?._id?.toString()).filter(Boolean);
      
      if (authorIds.length > 0) {
        const follows = await Follow.find({
          who: req.user.id,
          whom: { $in: authorIds },
        }).lean();
        follows.forEach(f => {
          followingMap[f.whom.toString()] = true;
        });
      }
      
      // Get likedByUser status for each story
      if (storyIds.length > 0) {
        const likes = await Like.find({
          story: { $in: storyIds },
          user: req.user.id,
        }).lean();
        likes.forEach(l => {
          likedMap[l.story.toString()] = true;
        });
      }
      
      // Get 2 most recent likers per story for \"Liked by X and Y others\" display
      if (storyIds.length > 0) {
        const allRecentLikes = await Like.find({ story: { $in: storyIds } })
          .sort({ createdAt: -1 })
          .populate("user", "fullName")
          .lean();
        
        // Take first 2 unique user likes per story
        for (const like of allRecentLikes) {
          const sid = like.story.toString();
          if (!recentLikersMap[sid]) recentLikersMap[sid] = [];
          if (recentLikersMap[sid].length < 2 && like.user?.fullName) {
            recentLikersMap[sid].push(like.user.fullName);
          }
        }
      }
    }

    // Attach following, liked status, and recent likers
    const enrichedStories = stories.map(s => ({
      ...s,
      followingAuthor: followingMap[s.author?._id?.toString()] || false,
      likedByUser: likedMap[s._id.toString()] || false,
      recentLikers: recentLikersMap[s._id.toString()] || [],
    }));

    res.json({
      success: true,
      data: {
        stories: enrichedStories,
        pagination: {
          page: type ? 1 : page,
          limit,
          total,
          pages: type ? 1 : Math.ceil(total / limit),
        },
      },
    });
  } catch (error) {
    next(error);
  }
}

export async function toggleLike(req, res, next) {
  try {
    const { storyId } = req.params;

    const story = await Story.findOne({
      _id: storyId,
      status: "published",
    }).select("_id author");

    if (!story) {
      throw new NotFoundError("Story not found.");
    }

    const existing = await Like.findOne({
      story: storyId,
      user: req.user.id,
    });

    if (existing) {
      await Promise.all([
        existing.deleteOne(),
        Story.findByIdAndUpdate(storyId, {
          $inc: {
            "stats.likes": -1,
          },
        }),
        // Decrement author likes count
        Author.findByIdAndUpdate(story.author, {
          $inc: { "stats.likes": -1 },
        }),
      ]);

      return res.json({
        success: true,
        data: {
          liked: false,
        },
      });
    }

    await Promise.all([
      Like.create({
        story: storyId,
        user: req.user.id,
      }),
      Story.findByIdAndUpdate(storyId, {
        $inc: {
          "stats.likes": 1,
        },
      }),
      // Increment author likes count
      Author.findByIdAndUpdate(story.author, {
        $inc: { "stats.likes": 1 },
      }),
    ]);

    res.json({
      success: true,
      data: {
        liked: true,
      },
    });
  } catch (error) {
    next(error);
  }
}

export async function getLikes(req, res, next) {
  try {
    const { storyId } = req.params;

    const likes = await Like.find({
      story: storyId,
    })
      .populate("user", "fullName avatar")
      .sort({
        createdAt: -1,
      })
      .lean();

    res.json({
      success: true,
      data: likes,
    });
  } catch (error) {
    next(error);
  }
}

export async function createComment(req, res, next) {
  try {
    const { storyId } = req.params;
    const { content } = req.body;

    if (!content?.trim()) {
      throw new ValidationError("Comment cannot be empty.");
    }

    const story = await Story.findOne({
      _id: storyId,
      status: "published",
    }).select("_id");

    if (!story) {
      throw new NotFoundError("Story not found.");
    }

    const comment = await Comment.create({
      story: storyId,
      user: req.user.id,
      content: content.trim(),
    });

    await Story.findByIdAndUpdate(storyId, {
      $inc: {
        "stats.comments": 1,
      },
    });

    const populated = await Comment.findById(comment.id)
      .populate("user", "fullName avatar")
      .lean();

    res.status(201).json({
      success: true,
      data: populated,
    });
  } catch (error) {
    next(error);
  }
}

export async function updateComment(req, res, next) {
  try {
    const { commentId } = req.params;
    const { content } = req.body;

    if (!content?.trim()) {
      throw new ValidationError("Comment cannot be empty.");
    }

    const comment = await Comment.findOne({
      _id: commentId,
      user: req.user.id,
    });

    if (!comment) {
      throw new NotFoundError("Comment not found.");
    }

    comment.content = content.trim();
    comment.edited = true;

    await comment.save();

    res.json({
      success: true,
      data: comment,
    });
  } catch (error) {
    next(error);
  }
}

export async function deleteComment(req, res, next) {
  try {
    const { commentId } = req.params;

    const comment = await Comment.findOne({
      _id: commentId,
      user: req.user.id,
    });

    if (!comment) {
      throw new NotFoundError("Comment not found.");
    }

    await Promise.all([
      comment.deleteOne(),
      Story.findByIdAndUpdate(comment.story, {
        $inc: {
          "stats.comments": -1,
        },
      }),
    ]);

    res.json({
      success: true,
      message: "Comment deleted successfully.",
    });
  } catch (error) {
    next(error);
  }
}

export async function getComments(req, res, next) {
  try {
    const { storyId } = req.params;

    const page = Math.max(Number(req.query.page) || 1, 1);
    const limit = Math.min(Number(req.query.limit) || 20, 50);

    const [comments, total] = await Promise.all([
      Comment.find({
        story: storyId,
      })
        .populate("user", "fullName avatar")
        .sort({
          createdAt: -1,
        })
        .skip((page - 1) * limit)
        .limit(limit)
        .lean(),

      Comment.countDocuments({
        story: storyId,
      }),
    ]);

    res.json({
      success: true,
      data: {
        comments,
        pagination: {
          page,
          limit,
          total,
          pages: Math.ceil(total / limit),
        },
      },
    });
  } catch (error) {
    next(error);
  }
}
