/**
 * Stable, machine readable error codes.
 *
 * Clients switch on `error.code`, never on the human readable message, so a
 * message can be improved without breaking a frontend.
 */
export const ERROR_CODES = {
  BAD_REQUEST: "BAD_REQUEST",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
  AUTHORIZATION_ERROR: "AUTHORIZATION_ERROR",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT_ERROR: "CONFLICT_ERROR",
  DUPLICATE_FIELD: "DUPLICATE_FIELD",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  STORAGE_ERROR: "STORAGE_ERROR",
  UPSTREAM_ERROR: "UPSTREAM_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};

/** HTTP status for every code — one table, one place to change. */
export const STATUS_BY_CODE = {
  [ERROR_CODES.BAD_REQUEST]: 400,
  [ERROR_CODES.VALIDATION_ERROR]: 422,
  [ERROR_CODES.AUTHENTICATION_ERROR]: 401,
  [ERROR_CODES.AUTHORIZATION_ERROR]: 403,
  [ERROR_CODES.FORBIDDEN]: 403,
  [ERROR_CODES.NOT_FOUND]: 404,
  [ERROR_CODES.CONFLICT_ERROR]: 409,
  [ERROR_CODES.DUPLICATE_FIELD]: 409,
  [ERROR_CODES.PAYLOAD_TOO_LARGE]: 413,
  [ERROR_CODES.TOO_MANY_REQUESTS]: 429,
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 503,
  [ERROR_CODES.STORAGE_ERROR]: 502,
  [ERROR_CODES.UPSTREAM_ERROR]: 502,
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: 500,
};
