import {
  HiOutlineLogin,
  HiOutlineLogout,
  HiOutlineExclamationCircle,
  HiOutlineCheckCircle,
  HiOutlineInformationCircle,
  HiOutlineMail,
  HiOutlineLockClosed,
  HiOutlineRefresh,
  HiOutlineSearch,
  HiOutlineX,
  HiOutlineClock,
  HiOutlineFilter,
  HiOutlineTrash,
  HiOutlineChartBar,
  HiOutlineTerminal,
  HiOutlineChevronLeft,
  HiOutlineChevronRight,
  HiOutlineChevronDown,
  HiOutlineShieldCheck,
  HiOutlineExclamation,
  HiOutlineCalendar,
  HiOutlinePause,
  HiOutlinePlay,
} from 'react-icons/hi';
import { FaSpinner, FaBug } from 'react-icons/fa';

export const Icons = {
  login: HiOutlineLogin,
  logout: HiOutlineLogout,
  exclamationCircle: HiOutlineExclamationCircle,
  exclamation: HiOutlineExclamation,
  checkCircle: HiOutlineCheckCircle,
  infoCircle: HiOutlineInformationCircle,
  mail: HiOutlineMail,
  lock: HiOutlineLockClosed,
  refresh: HiOutlineRefresh,
  search: HiOutlineSearch,
  close: HiOutlineX,
  clock: HiOutlineClock,
  filter: HiOutlineFilter,
  trash: HiOutlineTrash,
  chartBar: HiOutlineChartBar,
  terminal: HiOutlineTerminal,
  chevronLeft: HiOutlineChevronLeft,
  chevronRight: HiOutlineChevronRight,
  chevronDown: HiOutlineChevronDown,
  shieldCheck: HiOutlineShieldCheck,
  calendar: HiOutlineCalendar,
  pause: HiOutlinePause,
  play: HiOutlinePlay,
  spinner: FaSpinner,
  bug: FaBug,
};

export default Icons;
